name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: actions/checkout@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
