name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -name: Run Tests
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '19'
      - run: npm install
      - run: npm run build
      - run: npm run test
